services:
  seq-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15341:15341"
    volumes:
      - forwarder-data:/app/data
    stdin_open: true
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FORWARDER_DIAGNOSTICS_INTERNALLOGPATH=/app/data/logs/
      - FORWARDER_DIAGNOSTICS_INTERNALLOGGINGLEVEL=Information
      - FORWARDER_OUTPUT_SERVERURL=https://seq.example.com
      - FORWARDER_OUTPUT_EVENTBODYLIMITBYTES=262144
      - FORWARDER_OUTPUT_RAWPAYLOADLIMITBYTES=10485760
      - FORWARDER_OUTPUT_APIKEY=null
      - FORWARDER_STORAGE_BUFFERSIZESBYTES=67108864
      - FORWARDER_API_LISTENURI=http://localhost:15341

volumes:
  forwarder-data: